### PR TITLE
WIP -- Scheduler HA support

### LINKED ISSUE #15: Scheduler HA
We need to test and verify scheduler HA
- [x] preliminary scheduler lifecycle support
- [x] preliminary graceful failover support
- [x] we probably suffer from a similar issue https://github.com/mesosphere/marathon/issues/1063
  - potential solution: defer `buildFrameworkInfo()`/driver initialization until post-election
- [x] scheduler leader election
- [x] wire up leader election to graceful failover
- [x] executors commit suicide once they've "outlived their usefulness"
  - [x] multiple suicide attempts within 60s? see https://gist.github.com/jdef/70925988d01027a6fd8f
- [x] prevent multiple HA schedulers that will generate conflicting ExecutorInfo
  - [x] hash potentially conflicting `ExecutorInfo` and prepend to leader UID
  - [x] validate that current master has matching UID prefix, otherwise terminate
  - [x] what if all schedulers crash (there is no leader) then we start a new scheduler w/ diff params?
- [x] pass DNS parameters from scheduler to executor
  - [x] pass `Cluster{DNS,Domain}` from scheduler to executor
- [x] document how to make use of HA mode, requirements, etc.
  - `--ha` and `--km_path=hdfs:///...` is the easiest way to get started
  - if starting a secondary scheduler on the same host, use a different `--port`
  - all `--auth_path`, `--etcd_*`, `--executor_*`, and `--proxy_*` options must be identical
- [x] failover cleanup (lots of TODOs)
- [x] sync to latest version of osext to pick up https://github.com/kardianos/osext/commit/e61421bbfae9c64ff5836c1776b58b2deb34269f

Related upstream discussion
- https://github.com/GoogleCloudPlatform/kubernetes/issues/473

### PR DESCRIPTION
**Pull request by jdef**
- fixes #15 
- SIGUSR1 will trigger grafecul restart of scheduler proc
- `--ha` flag enables High Availability mode: multiple schedulers running w/ leader election
- auto-publish scheduler service to k8s service registry
- `--km-path` flag to specify path to all-in-one binary, accepts URI's (e.g. HDFS) as well as file paths
- introduce executor suicide timeout, defaults to `20m`
- scheduler rejects offers from slaves running "incompatible" executors
- intermittent pod registry reconciliation (triggered by specific task status update states)
- Makefile support for `golint`
- added "reasons" to metrics for declined offers

### CODE REVIEW

File: pkg/scheduler/ha/ha.go [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+		}
+		a()
+	}))
+}
+
+func (self *SchedulerProcess) Begin() {
+	if (&self.stage).transition(initStage, standbyStage) {
+		log.Infoln("scheduler process entered standby stage")
+		self.Process.Begin()
+		//TODO(jdef) start election listener
```
Comment (jdef) [inline pkg/scheduler/ha/ha.go]: remove TODO

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -105,12 +114,24 @@ func New(config Config) *KubernetesScheduler {
...
+				for _, eid := range o.GetExecutorIds() {
+					execuid := uid.Parse(eid.GetValue())
+					if execuid.Name() == execcfg.DefaultInfoID && execuid.Group() != k.executorGroup {
+						return false
+					}
+				}
+				return true
+			},
 			DeclineOffer: func(id string) error {
 				//TODO(jdef) only decline offers if we're connected/registered
```
Comment (jdef) [inline pkg/scheduler/scheduler.go]: would be nice to wrap this in proc.DoLater

File: pkg/executor/executor.go [hunk 3]
```diff
@@ -84,22 +118,34 @@ func New(kl *kubelet.Kubelet, ch chan<- interface{}, ns string, cl *client.Clien
...
+		kubeletFinished: config.KubeletFinished,
 	}
 	go k.sendLoop()
 	return k
 }
 
+func (k *KubernetesExecutor) Init(driver bindings.ExecutorDriver) {
+	k.killKubeletContainers()
+	k.resetSuicideWatch(driver)
+	//TODO(jdef) monitor kubeletFinished and shutdown if it happens
```
Comment (jdef) [inline pkg/executor/executor.go]: resolve this TODO

File: pkg/scheduler/service/publish.go [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+const (
+	SCHEDULER_SERVICE_NAME = "k8sm-scheduler"
+)
+
+func (m *SchedulerServer) serviceWriterLoop(stop <-chan struct{}) {
+	for {
+		// Update service & endpoint records.
+		// TODO: when it becomes possible to change this stuff,
+		// stop polling and start watching.
+		/*
```
Comment (jdef) [inline pkg/scheduler/service/publish.go]: remove dead code

File: pkg/scheduler/service/publish.go [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+
+		select {
+		case <-stop:
+			return
+		case <-time.After(10 * time.Second):
+		}
+	}
+}
+
+/*
```
Comment (jdef) [inline pkg/scheduler/service/publish.go]: remove dead code

File: pkg/scheduler/service/publish.go [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+	for i := range e.Endpoints {
+		if e.Endpoints[i] == endpoint {
+			found = true
+			break
+		}
+	}
+	if !found {
+		e.Endpoints = append(e.Endpoints, endpoint)
+	}
+	//TODO(jdef) we have no good way to specify the expected master count, so just hardcode this to
```
Comment (jdef) [inline pkg/scheduler/service/publish.go]: document this somewhere in the HA docs section

File: pkg/scheduler/service/service.go [hunk 7]
```diff
@@ -144,11 +176,28 @@ func (s *SchedulerServer) AddFlags(fs *pflag.FlagSet) {
...
 	fs.IntVar(&s.ExecutorLogV, "executor_logv", s.ExecutorLogV, "Logging verbosity of spawned executor processes.")
+	fs.DurationVar(&s.ExecutorSuicideTimeout, "executor_suicide_timeout", s.ExecutorSuicideTimeout, "Executor self-terminates after this period of inactivity. Zero disables suicide watch.")
 	fs.Int64Var(&s.ReconcileInterval, "reconcile_interval", s.ReconcileInterval, "Interval at which to execute task reconciliation, in sec. Zero disables.")
+	fs.DurationVar(&s.ReconcileCooldown, "reconcile_cooldown", s.ReconcileCooldown, "Minimum rest period between task reconciliation operations.")
+	fs.BoolVar(&s.Graceful, "graceful", s.Graceful, "Indicator of a graceful failover, intended for internal use only.")
+	fs.BoolVar(&s.HA, "ha", s.HA, "Run the scheduler in high availability mode with leader election. All peers should be configured exactly the same.")
+	fs.StringVar(&s.FrameworkName, "framework_name", s.FrameworkName, "The framework name to register with Mesos.")
+	fs.StringVar(&s.HADomain, "ha_domain", s.HADomain, "Domain of the HA scheduler service, only used in HA mode. If specified may be used to construct artifact download URIs.")
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: HA docs should spell out more clearly how this is used

File: pkg/scheduler/service/service.go [hunk 8]
```diff
@@ -183,22 +237,32 @@ func (s *SchedulerServer) prepareExecutorInfo(hks *hyperkube.Server) *mesos.Exec
...
 		ci.Value = proto.String(fmt.Sprintf("./%s", executorCmd))
 	} else if _, err := hks.FindServer(KM_EXECUTOR); err != nil {
 		log.Fatalf("either run this scheduler via km or else --executor_path is required: %v", err)
-	} else if filename, err := osext.Executable(); err != nil {
-		log.Fatalf("failed to determine path to currently running executable: %v", err)
 	} else {
-		uri, kmCmd := s.serveExecutorArtifact(filename)
-		ci.Uris = append(ci.Uris, &mesos.CommandInfo_URI{Value: proto.String(uri), Executable: proto.Bool(true)})
-		ci.Value = proto.String(fmt.Sprintf("./%s", kmCmd))
+		if strings.Index(s.KMPath, "://") > 0 {
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: Is this how the latest mesos fetcher determines URI presence?

File: pkg/scheduler/service/service.go [hunk 9]
```diff
@@ -282,6 +346,92 @@ func (s *SchedulerServer) createAPIServerClient() (*client.Client, error) {
 
 func (s *SchedulerServer) Run(hks *hyperkube.Server, _ []string) error {
 
+	schedulerProcess, dconfig, kpl, etcdClient, deferredInit, ehash := s.bootstrap(hks)
+	schedulerProcess.Begin()
+
+	go s.serviceWriterLoop(schedulerProcess.Done())
+
+	go util.Forever(func() {
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: use util.Until w/ schedulerProcess.Done()

File: pkg/scheduler/service/service.go [hunk 10]
```diff
@@ -331,83 +498,88 @@ func (s *SchedulerServer) Run(hks *hyperkube.Server, _ []string) error {
...
+	cmd := exec.Command(s.executable, args...)
+	cmd.Stdin = os.Stdin
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+	cmd.SysProcAttr = &syscall.SysProcAttr{
+		Setpgid: true, // disown the spawned scheduler
+	}
 
-func (s *SchedulerServer) buildFrameworkInfo(client tools.EtcdClient) (info *mesos.FrameworkInfo, cred *mesos.Credential, err error) {
+	// TODO(jdef) pass in a pipe FD so that we can block, waiting for the child proc to be read
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: clarify this comment

File: pkg/scheduler/service/service.go [hunk 11]
```diff
@@ -429,6 +601,29 @@ func (s *SchedulerServer) buildFrameworkInfo(client tools.EtcdClient) (info *mes
...
+			if !tools.IsEtcdNotFound(err) {
+				return nil, fmt.Errorf("unexpected failure attempting to load framework ID from etcd: %v", err)
+			}
+			log.V(1).Infof("did not find framework ID in etcd")
+		} else if response.Node.Value != "" {
+			log.Infof("configuring FrameworkInfo with Id found in etcd: '%s'", response.Node.Value)
+			return mutil.NewFrameworkID(response.Node.Value), nil
+		}
+	} else {
+		//TODO(jdef) this seems like a totally hackish way to clean up the framework ID
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: how do other frameworks do it?

File: pkg/scheduler/service/util.go [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+
+	mesos "github.com/mesos/mesos-go/mesosproto"
+)
+
+// compute a hashcode for ExecutorInfo that may be used as a reasonable litmus test
+// with respect to compatibility across HA schedulers. the intent is that an HA scheduler
+// should fail-fast if it doesn't pass this test, rather than generating (potentially many)
+// errors at run-time because a Mesos master decides that the ExecutorInfo generated by a
+// secondary scheduler doesn't match that of the primary scheduler.
+func hashExecutorInfo(info *mesos.ExecutorInfo) uint64 {
```
Comment (jdef) [inline pkg/scheduler/service/util.go]: for additional context, should probably include a link to mesos master code that performs executor spec validation

File: pkg/executor/executor.go [hunk 13]
```diff
@@ -187,9 +242,108 @@ func (k *KubernetesExecutor) LaunchTask(driver bindings.ExecutorDriver, taskInfo
 	k.tasks[taskId] = &kuberTask{
 		mesosTaskInfo: taskInfo,
 	}
+	k.resetSuicideWatch(driver)
+
 	go k.launchTask(driver, taskId, &pod)
 }
 
+// TODO(jdef) add metrics for this?
```
Comment (jdef) [inline pkg/executor/executor.go]: suicide metrics

File: pkg/scheduler/scheduler.go [hunk 14]
```diff
@@ -575,8 +777,7 @@ requestLoop:
 			case <-r.done:
```
Comment (jdef) [inline pkg/scheduler/scheduler.go]: Reconciler.done should probably point to the chan from electedMaster.Done()

File: pkg/scheduler/service/publish.go [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+)
+
+const (
+	SCHEDULER_SERVICE_NAME = "k8sm-scheduler"
+)
+
+func (m *SchedulerServer) serviceWriterLoop(stop <-chan struct{}) {
+	for {
+		// Update service & endpoint records.
+		// TODO: when it becomes possible to change this stuff,
```
Comment (jdef) [inline pkg/scheduler/service/publish.go]: TODO(k8s)

File: pkg/election/etcd_master.go [hunk 16]
```diff
@@ -0,0 +1,185 @@
...
+	"github.com/GoogleCloudPlatform/kubernetes/pkg/watch"
+	"github.com/coreos/go-etcd/etcd"
+	"github.com/golang/glog"
+)
+
+// Master is used to announce the current elected master.
+type Master string
+
+// IsAnAPIObject is used solely so we can work with the watch package.
+// TODO: Either fix watch so this isn't necessary, or make this a real API Object.
```
Comment (jdef) [inline pkg/election/etcd_master.go]: TODO(k8s)
