### PR TITLE
Constraints

### LINKED ISSUE #193: build fails on Mac
as reported by @nqn : `make` breaks with `readlink: illegal option -- f`

### PR DESCRIPTION
**Pull request by jdef**
First round of changes for constraints support. We want to walk snapshots of the task registry to evaluate pod placement and the older interfaces and implementation left much to be desired, including reliance upon the KubernetesScheduler state to guard against changes to pod tasks managed by the podtask.Registry. Ugh.

Changes here include:
- initial constraints interface, assimilated from Marathon
- refactor scheduler state locking
  - mesos scheduler `KubernetesScheduler` has its own lock (primarily for slave state)
  - plugin scheduler `k8smScheduler` has its own lock (for coordinating scheduler plugin ops)
- refactor `podtask.Registry` API
- panic metrics
- experimental "runtime" package w/ some conveniences
- support for building on windows within cygwin (requires env `CYGWIN=winsymlinks:native`)
- cleanup `proc` interfaces
- resolves #193 (building k8sm on osx/homebrew)
- fix racy failover/process termination

**TODO:**
- [x] investigate multiple data races

### CODE REVIEW

**Comment by jdef** [comment]
DATA RACE!!
```
WARNING: DATA RACE
Write by goroutine 57:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.(*T).FillFromDetails()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/pod_task.go:139 +0x30a
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*kubeScheduler).doSchedule()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/plugin.go:348 +0x8c2
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*kubeScheduler).Schedule()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/plugin.go:316 +0x694
  github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.(*Scheduler).scheduleOne()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/scheduler.go:72 +0x23f
  github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.*Scheduler.(github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.scheduleOne)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/scheduler.go:66 +0x33
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:101 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:102 +0xbb
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:86 +0x47

Previous read by goroutine 94:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.(*T).Clone()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/pod_task.go:77 +0x9e
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.(*inMemoryRegistry).List()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/registry.go:59 +0x1ce
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.func·002()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/debug.go:17 +0x95
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1235 +0x4d
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1511 +0x21c
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1673 +0x1fc
  net/http.(*conn).serve()
      /usr/local/go/src/pkg/net/http/server.go:1174 +0xf9e
  runtime.gosched0()
      /usr/local/go/src/pkg/runtime/proc.c:1436 +0xaf
  fmt.(*fmt).fmt_s()
      /usr/local/go/src/pkg/fmt/format.go:285 +0x74
  fmt.(*pp).fmtString()
      /usr/local/go/src/pkg/fmt/print.go:511 +0xf2
  fmt.(*pp).printArg()
      /usr/local/go/src/pkg/fmt/print.go:780 +0xd30
  fmt.(*pp).doPrintf()
      /usr/local/go/src/pkg/fmt/print.go:1159 +0x2aba
  fmt.Fprintf()
      /usr/local/go/src/pkg/fmt/print.go:188 +0x8c
  net/http.(*Request).write()
      /usr/local/go/src/pkg/net/http/request.go:393 +0x5e8
  net/http.(*persistConn).writeLoop()
      /usr/local/go/src/pkg/net/http/transport.go:891 +0x2aa
```

**Comment by jdef** [comment]
another DATA RACE!!
```
WARNING: DATA RACE
Write by goroutine 57:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*kubeScheduler).doSchedule()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/plugin.go:347 +0x887
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*kubeScheduler).Schedule()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/plugin.go:316 +0x694
  github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.(*Scheduler).scheduleOne()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/scheduler.go:72 +0x23f
  github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.*Scheduler.(github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler.scheduleOne)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/scheduler.go:66 +0x33
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:101 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:102 +0xbb
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:86 +0x47

Previous read by goroutine 151:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.(*T).Clone()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/pod_task.go:77 +0x9e
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.(*inMemoryRegistry).List()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/registry.go:59 +0x1ce
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask.func·002()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/podtask/debug.go:17 +0x95
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1235 +0x4d
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1511 +0x21c
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1673 +0x1fc
  net/http.(*conn).serve()
      /usr/local/go/src/pkg/net/http/server.go:1174 +0xf9e
  runtime.gosched0()
      /usr/local/go/src/pkg/runtime/proc.c:1436 +0xaf
  bytes.(*Buffer).WriteByte()
      /usr/local/go/src/pkg/bytes/buffer.go:228 +0x6a
  bytes.(*Buffer).WriteRune()
      /usr/local/go/src/pkg/bytes/buffer.go:239 +0x5c
  github.com/prometheus/client_golang/text.escapeString()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/text/create.go:311 +0x227
  github.com/prometheus/client_golang/text.MetricFamilyToText()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/text/create.go:59 +0x50a
  github.com/prometheus/client_golang/prometheus.(*registry).writePB()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/prometheus/registry.go:504 +0x1988
  github.com/prometheus/client_golang/prometheus.(*registry).ServeHTTP()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x160
  net/http.Handler.ServeHTTP·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/prometheus/http.go:58 +0x63
  github.com/prometheus/client_golang/prometheus.func·008()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/prometheus/client_golang/prometheus/http.go:144 +0x224
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1235 +0x4d
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1511 +0x21c
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/pkg/net/http/server.go:1673 +0x1fc
  net/http.(*conn).serve()
      /usr/local/go/src/pkg/net/http/server.go:1174 +0xf9e
```

**Comment by jdef** [comment]
3rd DATA RACE!!
```
WARNING: DATA RACE
Read by goroutine 81:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*KubernetesScheduler).storeFrameworkId()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/scheduler.go:280 +0x48
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.*KubernetesScheduler.(github.com/mesosphere/kubernetes-mesos/pkg/scheduler.storeFrameworkId)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/scheduler.go:305 +0x33
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:101 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:102 +0xbb

Previous write by goroutine 33:
  [failed to restore the stack]

Goroutine 81 (running) created at:
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*KubernetesScheduler).onInitialRegistration()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/scheduler.go:305 +0x6c9
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.func·023()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/scheduler.go:275 +0x6e
  sync.(*Once).Do()
      /usr/local/go/src/pkg/sync/once.go:40 +0xb1
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler.(*KubernetesScheduler).Registered()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/scheduler.go:275 +0x20e
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.func·005()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:147 +0xe5
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.stageType.When()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:52 +0x1ad
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.func·004()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:141 +0x6d
  github.com/mesosphere/kubernetes-mesos/pkg/proc.DoerFunc.Do()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/types.go:28 +0x56
  github.com/mesosphere/kubernetes-mesos/pkg/proc.func·005()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:150 +0xa5
  github.com/mesosphere/kubernetes-mesos/pkg/proc.func·001()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:44 +0x135
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:101 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:102 +0xbb

Goroutine 33 (running) created at:
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).Begin()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:47 +0xde
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).Begin()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:79 +0x141
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/service.(*SchedulerServer).Run()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/service/service.go:379 +0x194
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/service.func·001()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/service/service.go:157 +0x86
  github.com/GoogleCloudPlatform/kubernetes/pkg/hyperkube.(*HyperKube).Run()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/hyperkube/hyperkube.go:170 +0x749
  github.com/GoogleCloudPlatform/kubernetes/pkg/hyperkube.(*HyperKube).RunToExit()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/hyperkube/hyperkube.go:180 +0x52
  main.main()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/cmd/km/km.go:29 +0xe27
```

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/121

**Comment by jdef** [comment]
election `master_test.go` is still flaky, probably need to refactor use of WaitGroup:
```
panic: send on closed channel
goroutine 21 [running]:
github.com/mesosphere/kubernetes-mesos/pkg/election.(*slowService).Start(0xc20808f170)
	/home/travis/gopath/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/election/master_test.go:45 +0xe7
github.com/mesosphere/kubernetes-mesos/pkg/election.(*notifier).serviceLoop(0xc20802ec80)
	/home/travis/gopath/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/election/master.go:106 +0x343
created by github.com/mesosphere/kubernetes-mesos/pkg/election.Notify
	/home/travis/gopath/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/election/master.go:68 +0x1c5
goroutine 1 [runnable]:
syscall.Syscall(0x1, 0x1, 0xc20800a5c0, 0x5, 0x5, 0x5, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.write(0x1, 0xc20800a5c0, 0x5, 0x20, 0x45a04e, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1263 +0x6e
syscall.Write(0x1, 0xc20800a5c0, 0x5, 0x20, 0x4d4972, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:152 +0x58
os.(*File).write(0xc208030008, 0xc20800a5c0, 0x5, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:212 +0xb7
os.(*File).Write(0xc208030008, 0xc20800a5c0, 0x5, 0x20, 0xc208050101, 0x0, 0x0)
```

**Comment by jdef** [comment]
PTAL @vladimirvivien @guenter

File: pkg/scheduler/plugin.go [hunk 1]
```diff
@@ -37,78 +38,91 @@ const (
...
+	_, err := k.internal.driver.LaunchTasks(offerIds, taskList, filters)
 	return err
 }
 
 type binder struct {
-	api    SchedulerInterface
-	client *client.Client
+	api      schedulerInterface
+	client   *client.Client
+	rw       sync.RWMutex
```
Comment (jdef) [inline pkg/scheduler/plugin.go]: use an atomic.Value instead of RWMutex

File: pkg/scheduler/podtask/pod_task.go [hunk 2]
```diff
@@ -258,14 +303,15 @@ func RecoverFrom(pod api.Pod) (*T, bool, error) {
...
 		case annotation.OfferIdKey:
 			offerId = v
 		case annotation.TaskIdKey:
 			t.ID = v
-			t.TaskInfo.TaskId = mutil.NewTaskID(v)
 		case annotation.ExecutorIdKey:
-			t.TaskInfo.Executor = &mesos.ExecutorInfo{ExecutorId: mutil.NewExecutorID(v)}
+			// this is nowhere near sufficient to re-launch a task, but we really just
+			// want this for tracking
+			t.executor = &mesos.ExecutorInfo{ExecutorId: mutil.NewExecutorID(v)}
```
Comment (jdef) [inline pkg/scheduler/podtask/pod_task.go]: should we set `ExecutorInfo.Source` to something like `"recovery"` here, to be able to distinguish at some later point where this object came from?

File: pkg/scheduler/service/service.go [hunk 3]
```diff
@@ -380,19 +382,22 @@ func (s *SchedulerServer) Run(hks *hyperkube.Server, _ []string) error {
...
 
-	go util.Until(func() {
+	go runtime.Until(func() {
 		log.V(1).Info("Starting HTTP interface")
 		log.Error(http.ListenAndServe(net.JoinHostPort(s.Address.String(), strconv.Itoa(s.Port)), nil))
-	}, 5*time.Second, schedulerProcess.Done()) // TODO(jdef) extract constant
+	}, defaultHttpBindInterval, schedulerProcess.Done())
 
-	var driver bindings.SchedulerDriver
+	var driver atomic.Value // bindings.SchedulerDriver
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: would be better off implementing get/setDriver for SchedulerServer

File: pkg/scheduler/service/service.go [hunk 4]
```diff
@@ -405,40 +422,54 @@ func (s *SchedulerServer) Run(hks *hyperkube.Server, _ []string) error {
...
-		case <-schedulerProcess.Done():
-			select {
-			case <-schedulerProcess.Failover():
-				goto doFailover
-			default:
-				//TODO(jdef) should probably WARN here in HA mode
-				log.Infof("scheduler process exited without failover")
-			}
+	// we only want to return the first error (if any), everyone else can block forever
+	errCh := make(chan error, 1)
```
Comment (jdef) [inline pkg/scheduler/service/service.go]: use of errCh in this func smells bad.

**Comment by vladimirvivien** [comment]
@jdef I took a cursory look at the code.  The changes look good though the semantics escape me since I am still wrapping my head around the entire project.
